In [6]:
import pandas as pd
import numpy as np

data = {'car number': ['MU103', 'SY413', 'UR042', 'IG432'],
        'rank': [1,2,3,4],
        'speed': [50.5, 60.71, 70.43, 80.0],
        'acceleration': [2.3, 3.4, 4.7, 5.2]}
df = pd.DataFrame(data, index=range(1, 5))
colnames = list(df)
print(colnames)
df.index.name = 't/s'
print(df)
ns = np.array(df)
print(ns)

['car number', 'rank', 'speed', 'acceleration']
    car number  rank  speed  acceleration
t/s                                      
1        MU103     1  50.50           2.3
2        SY413     2  60.71           3.4
3        UR042     3  70.43           4.7
4        IG432     4  80.00           5.2
[['MU103' 1 50.5 2.3]
 ['SY413' 2 60.71 3.4]
 ['UR042' 3 70.43 4.7]
 ['IG432' 4 80.0 5.2]]


In [28]:
import pandas as pd
import numpy as np

data = {'rank': [1,2,3,4],
        'speed': [50, 60, 70, 80],
        'acceleration': [22, 33, 44, 55],
        'desire_speed': ['sp', 'fada', 'fafeqad', 'ed']}
df = pd.DataFrame(data)
print(df)
print(df['speed'].dtypes)
print(df['rank'].dtypes)
print(df['acceleration'].dtypes)
print(df['desire_speed'].dtypes)
nparr = np.array(df)
print(nparr)
y = list(nparr)
print(y)
x = nparr.tolist()
print(x)
type(x)

   rank  speed  acceleration desire_speed
0     1     50            22           sp
1     2     60            33         fada
2     3     70            44      fafeqad
3     4     80            55           ed
int64
int64
int64
object
[[1 50 22 'sp']
 [2 60 33 'fada']
 [3 70 44 'fafeqad']
 [4 80 55 'ed']]
[array([1, 50, 22, 'sp'], dtype=object), array([2, 60, 33, 'fada'], dtype=object), array([3, 70, 44, 'fafeqad'], dtype=object), array([4, 80, 55, 'ed'], dtype=object)]
[[1, 50, 22, 'sp'], [2, 60, 33, 'fada'], [3, 70, 44, 'fafeqad'], [4, 80, 55, 'ed']]


list

In [1]:
import pandas as pd
import numpy as np

data = {'rank': [1,2,3,4],
        'speed': [50, 60, 70, 80],
        'acceleration': [22, 33, 44, 55]}
df1 = pd.DataFrame(data)
nparr1 = np.array(df1)
print(nparr1)

[[ 1 50 22]
 [ 2 60 33]
 [ 3 70 44]
 [ 4 80 55]]


In [23]:
import pandas as pd
import numpy as np

data = {'rank': [1,2,3,4],
        'speed': [50, 60, 70, 80],
        'acceleration': [4, 5, 7, 2]}
df1 = pd.DataFrame(data)
print(df1)
nparr1 = np.array(df1)
print(nparr1)
x1=[1,2,3]
x2=(1,'hello',3.14,2,5.8,'fafa')
x3=3.14
x4={"Bob":39}
x5=4

   rank  speed  acceleration
0     1     50             4
1     2     60             5
2     3     70             7
3     4     80             2
[[ 1 50  4]
 [ 2 60  5]
 [ 3 70  7]
 [ 4 80  2]]


In [21]:
import pandas as pd
import numpy as np

df = pd.read_csv('D:\downloads\df_erweitert_Test.txt', sep=';',header=0)
df2 = df.head()
print(df2.values)
nparr = np.array(df.head())
#print(nparr)
print(type(nparr))
rand_array = np.random.rand(3,4)*100
print(rand_array)


[[ 6.700e+01  4.520e+02  4.390e+02  5.480e+01  5.380e+01  2.000e-01
   4.560e+02  4.800e+01  1.200e+01  3.000e+00  3.000e+00  3.000e+00
   3.000e+00  3.000e+00  3.000e+00  3.000e+00  0.000e+00  0.000e+00
   0.000e+00  4.100e+01  4.100e+01  4.585e+03]
 [ 6.700e+01  4.530e+02  4.390e+02  5.550e+01  5.380e+01  2.000e-01
   4.410e+02  4.800e+01  3.000e+00  3.000e+00  3.000e+00  3.000e+00
   3.000e+00  3.000e+00  3.000e+00  3.000e+00  0.000e+00  0.000e+00
   0.000e+00  4.100e+01  4.000e+01  4.585e+03]
 [ 6.700e+01  4.540e+02  4.390e+02  5.540e+01  5.380e+01 -0.000e+00
   4.250e+02  4.800e+01  3.000e+00  3.000e+00  3.000e+00  3.000e+00
   3.000e+00  3.000e+00  3.000e+00  3.000e+00  0.000e+00  0.000e+00
   0.000e+00  4.100e+01  3.900e+01  4.585e+03]
 [ 6.700e+01  4.550e+02  4.390e+02  5.470e+01  5.380e+01 -2.000e-01
   4.090e+02  4.800e+01  3.000e+00  3.000e+00  1.500e+01  3.000e+00
   3.000e+00  3.000e+00  3.000e+00  3.000e+00  0.000e+00  0.000e+00
   0.000e+00  4.100e+01  3.800e+01  4.585e+

In [20]:
x3=5.24549
print(type(x3))

<class 'float'>


In [2]:
import pandas as pd

def CtoPython(df):
    df['x1'] = pd.Series(df['x1'], dtype=int)
    df['x2'] = pd.Series(df['x2'], dtype=float)
    
    
    print(df)

In [4]:
import pandas as pd

df = pd.DataFrame(columns=['x1', 'x2'])
print(df)

Empty DataFrame
Columns: [x1, x2]
Index: []


['c:\\Users\\uk093878\\python', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\DLLs', 'C:\\Users\\uk093878\\python', 'c:\\Users\\uk093878\\Anaconda3\\envs\\kai\\python39.zip', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\lib', 'c:\\Users\\uk093878\\Anaconda3\\envs\\kai', '', 'C:\\Users\\uk093878\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\lib\\site-packages', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\lib\\site-packages\\win32', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\lib\\site-packages\\win32\\lib', 'C:\\Users\\uk093878\\Anaconda3\\envs\\kai\\lib\\site-packages\\Pythonwin']


In [1]:
import xgboost as xgb

In [2]:
import sklearn 

ModuleNotFoundError: No module named 'sklearn'